# This is a basic workflow to help you get started with Actions

name: Deploy to AWS production folder

# Controls when the action will run. 
on:
  # Triggers the workflow on tags
  push:
      tags:
      - 'v**'
      - '!v**.beta'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Create settings file
        id: add-settings
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "settings.json"
          json: ${{ secrets.GOOGLE_CREDENTIALS_JSON_PROD }}

      - name: Install and Build 🔧
        run: |
          yarn install
          yarn run build
           
      - name: Deploy docs to aws 🚀
        uses: jakejarvis/s3-sync-action@master
        env:
          SOURCE_DIR: dist/docs
          DEST_DIR: google-docs
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      - name: Deploy sheets to aws 🚀
        uses: jakejarvis/s3-sync-action@master
        env:
          SOURCE_DIR: dist/sheets
          DEST_DIR: google-sheets
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      - name: Deploy slides to aws 🚀
        uses: jakejarvis/s3-sync-action@master
        env:
          SOURCE_DIR: dist/slides
          DEST_DIR: google-slides
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      - name: Create CloudFront Cache Invalidation ☁️
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'us-west-1'